<div class="dqtContainer dqtFixed">
    <div id="dqtWorkflow">
        <div id="content">
            <h1>Welcome to the IRIS Data Query Tool</h1>


	<p class="description">The Data Query Tool (DQT) provides an interactive interface that enables you to view, compare, analyse and search the responses submitted by Member States as per their obligations under the following European Union (EU) Directives: Industrial Pollution Prevention and Control (including answers to questions aimed at specific IPPC sectors on Emission Limit Values and Best Available Techniques); Solvent Emissions; and Waste Incineration. The tool and its contents are available in English only.<br/><br/>
To read more about the DQT please click <a href="http://iris2.eionet.europa.eu/assets/downloads/Data-Query-Tool-User-Guide-v1-1.pdf" target="_blank">here</a> (DQT user guide).</p>

            <div id="options" class="roundedAll">
                <h2>Please make your selection from the available options</h2>

                <div id="colouredBand">
                    <a class="optionAction roundedAll" href="<?php echo $this->url(array('controller' => 'datasheet', 'action' => 'index')); ?>" title="Datasheet">Datasheet</a>
                    <a class="optionAction roundedAll" href="<?php echo $this->url(array('controller' => 'search', 'action' => 'index')); ?>" title="Datasheet">Search</a>
                    <a class="optionAction roundedAll" href="<?php echo $this->url(array('controller' => 'compare', 'action' => 'index')); ?>" title="Datasheet">Compare</a>
                </div>

                <div id="optionDescriptions">
                    <div class="option">
                        <p class="description">The datasheet option can be used to view Member State responses to each of the three European Directives on an individual basis.</p>
                    </div>

                    <div class="option">
                        <p class="description">The search option can be used to search through Member State datasheet responses - using keywords - by directive, reporting period and sector.</p>
                    </div>

                    <div class="option">
                        <p class="description">The compare option can be used to compare Member State responses submitted for a single Directive across one or two reporting periods.</p>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>