<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html lang="en_GB" xml:lang="en_GB" xmlns="http://www.w3.org/1999/xhtml">
    <head>
        <meta http-equiv="content-type" content="text/html; charset=utf-8" />
        <title>Data Query Tool - Industrial emissions Reporting Information System - Eionet</title>
        <meta http-equiv="content-language" content="en" />
        <meta name="keywords" content="Industrial emissions Reporting Information System, IRIS, Data Query Tool, Query Tool, DQT, European Union, Directives, Member States, Members, Responses, Integrated Pollution Prevention and Control, IPPC, Emission Limit Values, Best Available Techniques, ELV, BAT, ELV/BAT, Solvent Emissions, SE, Waste Incineration, WI" />
        <meta name="description" content="Industrial emissions Reporting Information System (IRIS) - Data Query Tool to provide an interactive interface to facilitate the comparison, analysis and searching of member state responses to European Union directives" />
        <link rel="stylesheet" type="text/css" href="<?php echo $this->baseUrl('stylesheets/chart_layout.css'); ?>" media="screen" />
        <link rel="shortcut icon" href="http://www.eionet.europa.eu/favicon.ico" type="image/vnd.microsoft.icon" />
        <link rel="icon" href="http://www.eionet.europa.eu/styles/eionet2007/eeaicon.gif" type="image/gif" />
        <script type="text/javascript" src="<?php echo $this->baseUrl('javascripts/js-class.js'); ?>"></script>
        <script type="text/javascript" src="<?php echo $this->baseUrl('javascripts/bluff.min.js'); ?>"></script>
        <script type="text/javascript" src="<?php echo $this->baseUrl('javascripts/excanvas.js'); ?>"></script>
        <script type="text/javascript">
            /*<![CDATA[*/
            var _gaq = _gaq || [];
            _gaq.push(['_setAccount', 'UA-20285006-2']);
            _gaq.push(['_trackPageview']);

            (function() {
                var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
                ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
                var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
            })();
            /*]]>*/
        </script>
    </head>

    <body>
        <?php echo $this->layout()->content; ?>
    </body>
</html>