<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.1//EN" "http://www.w3.org/TR/xhtml11/DTD/xhtml11.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en-gb">
    <head>
        <meta http-equiv="content-type" content="text/html; charset=utf-8" />
        <title><?php echo $this->title; ?> - Industrial emissions Reporting Information System (IRIS) - Eionet</title>
        <meta http-equiv="content-language" content="en" />
        <meta name="keywords" content="Industrial emissions Reporting Information System, IRIS, Data Query Tool, Query Tool, DQT, European Union, Directives, Member States, Members, Responses, Integrated Pollution Prevention and Control, IPPC, Emission Limit Values, Best Available Techniques, ELV, BAT, ELV/BAT, Solvent Emissions, SE, Waste Incineration, WI" />
        <meta name="description" content="Industrial emissions Reporting Information System (IRIS) - Data Query Tool to provide an interactive interface to facilitate the comparison, analysis and searching of member state responses to European Union directives" />
        <link rel="shortcut icon" href="http://www.eionet.europa.eu/favicon.ico" type="image/vnd.microsoft.icon" />
        <link rel="icon" href="http://www.eionet.europa.eu/styles/eionet2007/eeaicon.gif" type="image/gif" />
        <link rel="start" title="Home" href="/" />
        <link rel="alternate" type="application/rss+xml" title="Eionet headlines" href="http://www.eionet.europa.eu/announcements.rdf" />
        <link rel="stylesheet" type="text/css" href="http://www.eionet.europa.eu/styles/eionet2007/screen.css" media="screen" />
        <script type="text/javascript" src="http://www.eionet.europa.eu/styles/eionet2007/pageops.js"></script>
        <?php echo $this->headLink(); ?>
        <?php echo $this->headScript(); ?>
        <script type="text/javascript">
            /*<![CDATA[*/
            var _gaq = _gaq || [];
            _gaq.push(['_setAccount', 'UA-20285006-2']);
            _gaq.push(['_trackPageview']);

            (function() {
                var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
                ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
                var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
            })();
            /*]]>*/
        </script>
    </head>

    <body>
        <div id="container">
            <div id="toolribbon">
                <div id="lefttools">
                    <a id="skiplink" href="#workarea" accesskey="2"><span>Skip to content</span></a>
                    <a id="eealink" href="http://www.eea.europa.eu/">EEA</a>
                    <a id="ewlink" href="http://ew.eea.europa.eu/">EnviroWindows</a>
                </div>

                <div id="righttools">
                    <a href="<?php echo $this->cmsBaseUrl('Security/login'); ?>" id="loginlink">Login</a>
                    <a id="printlink" title="Print this page" href="javascript:this.print();"><span>Print</span></a>
                    <a id="fullscreenlink" href="javascript:toggleFullScreenMode()" title="Switch to/from full screen mode"><span>Switch to/from full screen mode</span></a>
                    <a id="acronymlink" href="/acronyms" title="Look up acronyms"><span>Acronyms</span></a>
                    <a id="rsslink" type="application/rss+xml" href="http://www.eionet.europa.eu/announcements.rdf" title="Eionet headlines as RSS"><span>RSS</span></a>
                    <form method="get" action="<?php echo $this->cmsBaseUrl('home/search'); ?>">
                        <div id="freesrchform">
                            <label for="freesrchfld">Search</label>
                            <input id="freesrchfld" type="text" name="q" value="Search IRIS" title="Search IRIS" onblur="if(this.value == '') this.value = 'Search IRIS';" onfocus="if(this.value == 'Search IRIS') this.value = '';" />
                            <input id="freesrchbtn" type="image" alt="Search" src="http://www.eionet.europa.eu/styles/eionet2007/button_go.gif" />
                        </div>
                    </form>
                </div>
            </div><!-- toolribbon -->

            <div id="pagehead">
                <a title="Frontpage" href="<?php echo $this->cmsBaseUrl(); ?>"><img src="http://www.eionet.europa.eu/styles/eionet2007/eea-print-logo.gif" alt="Logo" id="logo" width="428" height="87" /></a>
                <div id="networktitle">Eionet</div>
                <div id="sitetitle">Industrial emissions Reporting Information System (IRIS)</div>
                <div id="sitetagline"></div>
            </div>

            <div id="menuribbon">
                <?php echo $this->eionetNavigation('header'); ?>
            </div>

            <div class="breadcrumbtrail">
				<div class="breadcrumbhead">You are here:</div>
				<div class="breadcrumbitem eionetaccronym"><a href="http://www.eionet.europa.eu">Eionet</a></div>
				<div class="breadcrumbitem"><a href="<?php echo $this->cmsBaseUrl(); ?>">IRIS II</a></div>
				<?php echo $this->breadcrumbTrail($this->breadcrumbTrail); ?>
				<div class="breadcrumbtail"></div>
			</div>

            <div id="contentWrapper">
                <?php if($this->showLeftNavigation): ?>
                    <div id="leftcolumn">
                        <?php echo $this->eionetNavigation('left', $this->ssPage); ?>
                    </div>
                <?php endif; ?>
                
                <div id="workarea">
                    <div id="irisContent">
                        <div id="dqtLoading" class="roundedAll">
                            <p><img src="<?php echo $this->baseUrl('images/small_loader.gif') ?>" alt="Loading" /> Loading data...</p>
                        </div>

                        <?php echo $this->partial('flashMessages.phtml', array('flashMessages' => $this->flashMessages)); ?>
                        <?php echo $this->layout()->content; ?>
                    </div>
                </div>
            </div>
        </div>

        <div id="pagefoot">
            <p>
                <a href="http://www.eea.europa.eu/legal/copyright" title="&copy; Copyright 1995 - 2008">&copy; Copyright 1995 - 2008</a>,
                <a href="http://www.eea.europa.eu/legal/disclaimer" title="Disclaimer">Disclaimer</a>,
                <a href="http://www.eea.europa.eu/legal/privacy" title="Privacy Policy">Privacy Policy</a>,
                Contact <a href="http://www.eea.europa.eu/help/contact-info" title="EEA Web Team">EEA Web Team</a>,
                Contact <a href="<?php echo $this->url(array('controller' => 'contact', 'action' => 'index'), 'default'); ?>" title="DG Environment">DG Environment</a>,
                <a href="http://ec.europa.eu/environment/air/pollutants/stationary/ippc/index.htm" title="IPPC Europa">IPPC Europa</a>
            </p>
        </div>
    </body>
</html>